---
- name: restart hadoop-hdfs-namenode
  service: name=hadoop-hdfs-namenode state=restarted
  ignore_errors: yes

- name: restart hadoop-hdfs-datanode
  service: name=hadoop-hdfs-datanode state=restarted
  ignore_errors: yes

- name: restart hadoop-hdfs-journalnode
  service: name=hadoop-hdfs-journalnode state=restarted
  ignore_errors: yes

- name: refresh datanodes
  sudo_user: hdfs
  command: hdfs dfsadmin -refreshNodes
  ignore_errors: yes
