---
# Global Parameters

# Cluster name
site_name: HA_HDFS_Cluster

hadoop:
  dfs_dir_parent: /data/hadoop
  dfs_dir_nn: /nn
  dfs_dir_jn: /jn
  dfs_dir_dn: [ /data/hadoop/dn, /data01/hadoop/dn, /data02/hadoop/dn ]

hdfs_version: "2.5.0+cdh5.3.*"
hdfs_conf_dir: "/etc/hadoop/conf"
hdfs_namenode: False
hdfs_namenode_host: localhost
hdfs_namenode_port: 8020
hdfs_group: hdfs
hdfs_uid: 3090
hdfs_gid: 3090
hdfs_user: hdfs
hdfs_disks: []

hdfs_core_properties:
  - { name: "fs.defaultFS", value: "hdfs://{{ hdfs_namenode_host }}:{{ hdfs_namenode_port }}" }
hdfs_namenode_properties:
  - { name: "dfs.permissions.superusergroup", value: "hadoop" }
  - { name: "dfs.namenode.name.dir", value: "/media/persistent0" }
hdfs_datanode_properties:
  - { name: "dfs.permissions.superusergroup", value: "hadoop" }
  - { name: "dfs.datanode.data.dir", value: "{{ hdfs_disks | map(attribute='mount_point') | join(',') }}" }
